### ISSUE TITLE
Tooltip position is not under icon , on scroll tooltip is coming somewhere on the screen not below the icon.

### ISSUE THREAD

**Issue by nidhiag** [carbon-design-system/carbon-components-react#77] opened 2017-07-04 12:01 UTC
I am using the Tooltip from the latest react component . But in the storybook i can see this . On changing the resolution or scrolling on screen tooltip leaves the icon . Please see the screenshot .
![image](https://user-images.githubusercontent.com/22441670/27829304-9ab2af80-60de-11e7-8aca-73874be689ce.png)

**Comment by nidhiag** [comment] 2017-07-05 06:06
Please reply

**Comment by chrisdhanaraj** [comment] 2017-07-05 15:32
@nidhiag - we try to PRs as soon as possible, but it may not be the day of or the next day (especially when that day is a national holiday).

**Comment by hellobrian** [comment] 2017-07-10 04:34
Can you check again? I'm not able to reproduce the bug you're seeing @nidhiag: [React Storybook Tooltip](http://react.carbondesignsystem.com/?selectedKind=Tooltip&selectedStory=position&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel)

Works on:
- macOS Sierra 10.12.5: 
  - Chrome 58.0.3029.110 (64-bit)
  - Firefox 54.0.1 (64-bit)
  - Safari 10.1.1 (12603.2.4)

**Comment by nidhiag** [comment] 2017-07-10 05:00
Hi Brian , 
I am still facing the same issue. I am using the styles from 
require('carboncomponents/css/carbon-components.css');
require('carboncomponents/scss/components/tooltip/_tooltip.scss');

My webpack-config file is as below : 

var path = require('path');

var webpack = require('webpack');
var CopyWebpackPlugin = require('copy-webpack-plugin');
const autoprefixer = require('autoprefixer');

var dir_js = path.resolve(__dirname, 'src/client');
var dir_html = path.resolve(__dirname, 'src/client');
var dir_build = path.resolve(__dirname, 'build');
require('es6-promise').polyfill();

module.exports = {
    entry: [path.resolve(dir_js, 'index.js'), 'webpack-hot-middleware/client'],
    output: {
        path: dir_build,
        filename: 'bundle.js'
    },
    devServer: {
        contentBase: dir_build,
    },
    module: {
        loaders: [
            {
                loader: 'react-hot-loader',
                test: dir_js,
            },
            {
                loader: 'babel-loader',
                test: dir_js,
                query: {
                    presets: ['es2015', 'react'],
                },
            },

            {
                test: /\.css$/,
                loader: 'style-loader!css-loader'
            },
            {
                test: /\.sass/,
                loader: 'style-loader!css-loader!sass-loader?outputStyle=expanded&indentedSyntax'
            },

            {
                test: /\.scss$/,
                use: ['style-loader', 'css-loader','sass-loader' ],
            },
            /*{
                test: /\.scss$/,
                loader: 'style-loader!css-loader!sass-loader?outputStyle=expanded'
            },*/
            {
                test: /\.less/,
                loader: 'style-loader!css-loader!less-loader'
            },
            {
                test: /\.styl$/,
                loader: 'style-loader!css-loader!stylus-loader'
            },
            {
                test: /\.(png|jpg|gif|woff|woff2|otf)(\?.*$|$)/,
                loader: 'url-loader?limit=8192'
            },
            {
                test: /\.(ttf|eot|mp4|ogg|svg)(\?.*$|$)/,
                loader: 'file-loader'
            }
        ]
    },
    plugins: [
        // Simply copies the files over
        new CopyWebpackPlugin([
            { from: dir_html } // to: output.path
        ]),
        new webpack.optimize.OccurrenceOrderPlugin(),
   		new webpack.HotModuleReplacementPlugin(),
        // Avoid publishing files when compilation fails
        new webpack.NoEmitOnErrorsPlugin(),
        new webpack.LoaderOptionsPlugin({
            options: {
                context: __dirname,
                postcss: [
                    autoprefixer
                ]
            }
        })


    ],
    stats: {
        // Nice colored output
        colors: true
    },
    resolve: {    
    alias: {
      carboncomponents: path.resolve(__dirname, '.', 'node_modules/carbon-components/')
    }
  },
    // Create Sourcemaps for the bundle
    devtool: 'source-map'
};

**Comment by hellobrian** [comment] 2017-07-10 05:29
When you use `path.resolve`, do you need the `'.'` argument? Maybe it should be just the following:

```js
resolve: {    
    alias: {
      carboncomponents: path.resolve(__dirname, 'node_modules/carbon-components/')
    }
},
```

(Apologies, I'm not super familiar with Webpack just yet to debug your problem like this.)

As a sanity check, can you try using the [Unpkg CDN for CSS](https://unpkg.com/carbon-components@7.13.2/css/carbon-components.min.css) to see if you're still getting the same style errors? 

Using this could help determine whether the issue is with the stylesheets or with webpack

**Comment by nidhiag** [comment] 2017-07-10 11:20
Hi Brian , 
I used CDN but same issue .
<link rel="stylesheet" href="https://unpkg.com/carbon-components@7.13.1/css/carbon-components.min.css">
tooltip content is fixed at the first time position and on scroll the tooltip is not coming under icon. 
![image](https://user-images.githubusercontent.com/22441670/28015908-ceb550d4-658f-11e7-9876-c5980ace6466.png)

**Comment by nidhiag** [comment] 2017-07-10 11:21
<img width="453" alt="screen shot 2017-07-06 at 10 37 31 am" src="https://user-images.githubusercontent.com/22441670/28015948-ee6da75a-658f-11e7-9d39-5aba97327a34.png">

**Comment by nidhiag** [comment] 2017-07-10 11:26
@hellobrian 
Do i need to raise issue in cloudplatform slack channel ?

**Comment by chrisdhanaraj** [comment] 2017-07-10 12:26
This is resolved by https://github.com/carbon-design-system/carbon-components-react/pull/81

**Comment by iangfleming** [comment] 2017-07-10 14:16
@nidhiag I just merged a PR that should fix your issue.

**Closed by iangfleming** 2017-07-10 14:16 UTC
Labels: bug

**Comment by nidhiag** [comment] 2017-07-11 05:10
Issue got resolved with the latest code 👍 Many thanks .
