### ISSUE TITLE
UI shell story source has `Undefined` component names

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-components-react#1967] opened 2019-03-04 20:37 UTC
When building an application with the UI shell, I turned to the experimental React storybook > UI Shell > Header, then top-right "Show Info".

Looking to copy/paste the story source into my application, I couldn't because some component names are `Undefined`. The story source:

```
<Header>
<HeaderMenuButton aria-label="Open menu" onClick={Menu clicked} />
<HeaderName href="#">
[Platform]
</HeaderName>
<HeaderNavigation aria-label="IBM [Platform]">
<Unknown href="#">
Catalog
</Unknown>
<Unknown href="#">
Docs
</Unknown>
<Unknown href="#">
Support
</Unknown>
<Unknown aria-label="Manage">
<Unknown href="#">
Link 1
</Unknown>
<Unknown href="#">
Link 2
</Unknown>
<Unknown href="#">
Link 3
</Unknown>
</Unknown>
</HeaderNavigation>
<HeaderGlobalBar>
<HeaderGlobalAction aria-label="Notifications" onClick={notification click}>
<Notification16/>
</HeaderGlobalAction>
<HeaderGlobalAction aria-label="Profile" onClick={user click}>
<User16/>
</HeaderGlobalAction>
</HeaderGlobalBar>
</Header>
```

**Comment by asudoh** [comment] 2019-03-04 23:27
Hi 👋 @mattrosno you can click on STORY tab at the bottom and see the actual code. We know that there are some problems with Story Source section of the info add-on.

**Comment by asudoh** [comment] 2019-05-02 03:49
Duplicate of: #1563

**Closed by asudoh** 2019-05-02 03:49 UTC
Labels: wontfix
