### ISSUE TITLE
onClick does not work on InteriorLeftNavItem

### ISSUE THREAD

**Issue by Kenzku** [carbon-design-system/carbon-components-react#225] opened 2017-09-08 09:07 UTC
tried on this
```
this._onItemClicked = this. _onItemClicked(this);
....

<InteriorLeftNavItem label={...} href={...} children={...} onClick={this. _onItemClicked}/>
```
but the onClick event is not picked up.

Same code works for `InteriorLeftNav`

**Comment by joshblack** [comment] 2017-11-03 01:44
Thanks for reporting! I believe this is a duplicate of #197, so closing this in favor of that issue.

If you believe this is a mistake, feel free to re-open with any clarifications!

**Closed by joshblack** 2017-11-03 01:44 UTC
Labels: bug
