### ISSUE TITLE
DatePicker minDate and maxDate not working

### ISSUE THREAD

**Issue by AdrianM20** [carbon-design-system/carbon-components-react#907] opened 2018-05-21 15:27 UTC
Hello! Today I tried using the minDate and maxDate properties of the DatePicker but I noticed they are not working. I still can choose dates outside the established range. I would say this is a bug that did not come up to anyone yet.

**Comment by joshblack** [comment] 2018-05-21 17:48
Hi @AdrianM20! 👋 Thanks so much for taking the time to make this issue 🙂 Could you help us isolate this issue by making a Codesandbox link with the unexpected behavior you're experiencing? Would help us out a ton! 🙏

**Comment by AdrianM20** [comment] 2018-05-21 18:47
Okay, so I tried reproducing my context in the codesandbox but aparently in sandbox the datepicker is not working at all. In my project it works as expected except the min and max date. Here you have the sandbox.

[![Edit q7897jpqmj](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/q7897jpqmj)

**Comment by tw15egan** [comment] 2018-05-21 18:59
I tried reproducing this issue, but it works fine for me: 

https://codesandbox.io/s/kxlwyj7635

**Comment by AdrianM20** [comment] 2018-05-21 19:11
Well something is broken in the sandbox I created because the CSS is not loading. Regardless, in my project the datepicker is not restricted.
Code block from my project:
```<DatePicker
    id="start-date-picker"
    name="startDate"
    datePickerType="single"
    dateFormat="d/m/Y"
    onChange={(e) => this.handleFormUpdates('startDate', e[0])}
    minDate="20/5/2018"
>
    <DatePickerInput 
        labelText="Start date"
        placeholder="Date..."
        id="start-date-picker-input"
    />
</DatePicker>```

**Comment by tw15egan** [comment] 2018-05-21 19:12
You'll need to load the styles from `https://unpkg.com/carbon-components@8.22.6/css/carbon-components.css`

**Comment by tw15egan** [comment] 2018-05-21 19:13
I just copied your code block into codesandbox and cannot reproduce either, so you might need to ensure your `carbon-components-react` is up to date

**Comment by AdrianM20** [comment] 2018-05-21 19:16
I am using version 5.49.3. I will try to update it tomorrow at work and come with a feedback. Thank you for your time 😄

**Comment by joshblack** [comment] 2018-05-21 19:18
Going to close this for now given that we can't find a reliable way to reproduce. Feel free to re-open if that's not the case tomorrow!

**Closed by joshblack** 2018-05-21 19:18 UTC
Labels: bug, needs repro
