### ISSUE TITLE
FileUploaderButton: Ability to set a clickable Icon instead of a button

### ISSUE THREAD

**Issue by itdove** [carbon-design-system/carbon-components-react#1085] opened 2018-07-13 18:22 UTC
I have to add in a data-table an action in order to upload a file from the client to the server.
For the time being I use the FileUploaderButton but having a big button in the data table is not so nice. An icon would be much nicer.

Something like (with of course another icon than the trash ;-):
<img width="1541" alt="image" src="https://user-images.githubusercontent.com/28610057/42707402-15271586-86a8-11e8-841c-a6ebedea9613.png">

rather than

<img width="728" alt="image" src="https://user-images.githubusercontent.com/28610057/42707431-2abc2b98-86a8-11e8-9dda-c361fae7c3fe.png">

**Comment by asudoh** [comment] 2019-05-02 01:21
Closing as a duplicate of: #1071

**Closed by asudoh** 2019-05-02 01:21 UTC
Labels: type: enhancement 💡, type: visual :art:, wontfix
