### ISSUE TITLE
Tooltip: doesn't have provider from the react app

### ISSUE THREAD

**Issue by nelsonchen90** [carbon-design-system/carbon-components-react#742] opened 2018-03-23 15:24 UTC
## Detailed description

> Describe in detail the issue you're having.

Since the tooltip component will be rendered under body, it's not inside the react app provider hence it doesn't have any of the provider in the context/props. 
1. For example, when we use `react-intl`, it requires all components being rendered with in the `<IntlProvider>`, but the Tooltip is actually being rendered as a sibling of the `<IntlProvider>`

2. Another similar example is react-redux.

> Is this a feature request (new component, new icon), a bug, or a general issue?

general issue

> Is this issue related to a specific component?

Yes, Tooltip

> What did you expect to happen? What happened instead? What would you like to see changed?

I expect the way to use tooltip to be the same as normal components.

> What browser are you working in?

it's not related to any browser

> What version of the Carbon Design System are you using?

5.30.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Information server/Unified governance.

## Steps to reproduce the issue

1. use react-redux
2. use a component connected to redux state as the content of the tooltip, 
3. when hover on the trigger text, you will see the error.

## Additional information

* Screenshots or code
* Notes

**Comment by psachs21** [comment] 2018-03-31 20:44
@nelsonchen90 I believe this issue is resolved with react v16, with the introduction of portals. I haven't tested myself, but which version of React are you using?

**Comment by nelsonchen90** [comment] 2018-04-01 00:40
@psachs21 we are on v15 and planning to upgrade to v16 very soon. I will ref this issue to the upgrade story. Thanks!

**Comment by joshblack** [comment] 2018-04-02 15:29
Hey @nelsonchen90! 👋 Thanks so much for taking the time to make this issue 😄 

Could you try and reproduce with the codesandbox link in the PR template? Specifically this link: https://codesandbox.io/s/x2mjypo6pp (or a custom one if this doesn't match your environment). Would help a ton to track this bug down. Thanks!

**Comment by nelsonchen90** [comment] 2018-04-16 19:00
@psachs21 We tested on React 16, it doesn't seem be to working tho. 
I assume we don't need to implement the `Portal` or anything from our side, right?

**Comment by psachs21** [comment] 2018-04-16 19:15
@nelsonchen90 I'll echo @joshblack then, a reproduction would be helpful. I created a basic example here: https://codesandbox.io/s/kkro1vvzo3 but was not able to reproduce.

**Comment by nelsonchen90** [comment] 2018-04-16 19:33
@psachs21 Hmm, I forked yours and added the router stuff. and it's working too. https://codesandbox.io/s/qqrv60yn09
we are also in the process of upgrading to the latest React router too - which is being used in the sandbox, maybe that also helped?

**Comment by psachs21** [comment] 2018-04-16 20:50
@nelsonchen90 sorry I couldn't be more help.

**Comment by joshblack** [comment] 2018-04-23 18:58
Going to close this for now until we can get a link to reproduce. Feel free to re-open if that issue still persists!

**Closed by joshblack** 2018-04-23 18:58 UTC
