### ISSUE TITLE
Button component takes user specified className as the first CSS class

### ISSUE THREAD

**Issue by AdrianM20** [carbon-design-system/carbon-components-react#843] opened 2018-04-27 12:13 UTC
Hi! Today I wanted to customise the style of a button and I noticed that regardless of my style settings the button did not change. After some digging I found out that the className element of the Button is placed as the first class in the CSS class string. I think this could be considered a bug since it should be the last class in the string so that a user CSS style overrides the default Button classes from the Carbon style sheet. Is it possible to modify this?

**Comment by tw15egan** [comment] 2018-05-04 19:53
Hmm, I'm not able to reproduce this. By passing a custom class to the `Button` component, and then styling `.some-class: { color: red; background-color: red; }`, I get this:

<img width="645" alt="screen shot 2018-05-04 at 2 52 41 pm" src="https://user-images.githubusercontent.com/11928039/39649280-e97389a8-4faa-11e8-8885-69105282049d.png">

**Comment by AdrianM20** [comment] 2018-05-04 20:28
I will get to you with some screenshots once I get home. As you can see in your example, some-class is not the last applied style but the button.bx--btn. If you would have for example a display:block in some-class the display prop in button.bx-btn would replace it.

**Comment by AdrianM20** [comment] 2018-05-07 08:41
As I said previously about your example and now in mine too, the user style class applied to the Button is not the last one in the class string thus users styles cannot override default Button styles.

![button bug](https://user-images.githubusercontent.com/23298456/39693052-606c60ce-51eb-11e8-813b-1eb397195a05.png)

**Comment by joshblack** [comment] 2018-05-07 14:56
Hi @AdrianM20! 👋 Could this situation be resolved by increasing the specificity of the selector so that it takes precedence over the button styles you're trying to override?

**Comment by i-a-n** [comment] 2018-05-07 15:39
@AdrianM20 it's not the order of the classes as they appear on the element that determine the CSS priority in this case. see this codepen example: https://codepen.io/ianm/pen/qYVxeZ

the reason `button.bx--btn` is taking precedence in your example is that it's more specific than `.some-class`. you can add specificity to your `.some-class` selector (perhaps calling it `.signOut-button .some-class`) to work around that.

the question of whether Carbon should be less specific (perhaps dropping `button` from the selector) is a design system question and the Carbon team can make that call, it's a fairly standard practice but I don't think it's vital, and probably can be updated. just my two cents.

**Comment by AdrianM20** [comment] 2018-05-07 16:05
I will try tomorrow at work to increase the specificity to see if this could be a solution or a workaround. Thank you for your help. I will keep you updated.

**Comment by joshblack** [comment] 2018-05-10 18:26
Closing this for now, feel free to re-open if the issue still exists!

**Closed by joshblack** 2018-05-10 18:26 UTC
Labels: bug
