### ISSUE TITLE
Table Row should handle firefox outline issue 

### ISSUE THREAD

**Issue by chenzhh** [carbon-design-system/carbon-components-react#229] opened 2017-09-09 03:44 UTC
Table Row component's outline is not proper displayed when descendant elements is out of bounds.
![image](https://user-images.githubusercontent.com/12123055/30236754-ca0e5640-9553-11e7-96ce-6306a14ce0ce.png)
Which is caused by a firefox know issue: https://bugzilla.mozilla.org/show_bug.cgi?id=687311
Please help to fix.

**Comment by joshblack** [comment] 2017-11-03 01:46
Hi there! 👋 

Thanks so much for reporting this issue. I believe it's a duplicate of #196, so closing this in favor of that issue.

If you believe this is an error, feel free to re-open this issue with any clarifications you feel are necessary!

**Closed by joshblack** 2017-11-03 01:46 UTC
Labels: bug
