### ISSUE TITLE
Multiselect items v. selected items

### ISSUE THREAD

**Issue by kershnerd** [carbon-design-system/carbon-components-react#725] opened 2018-03-19 19:01 UTC
I have tried this a hundred ways, but I can't seem to get this to work.

My control has this state:
    this.state = {
      items: [
        {
          id: 'option-1',
          label: 'Option 1',
          checked: true
        },
        {
          id: 'option-2',
          label: 'Option 2',
          checked: false
        }
      ]
    }

Setting my items to this works:
items={ this.state.items }

Setting initialSelectedItems like this seems to work:
initialSelectedItems={ this.state.items.filter(x => x.checked) }

But unchecking the selected item keeps getting checked again when I leave the control.  It seems that the initialSelectedItems never gets cleared.

I am sure I just just using this incorrectly.  Any suggestions?

**Comment by joshblack** [comment] 2018-03-19 19:40
Hi @kershnerd! 👋 thanks so much for taking the time to make this issue 😄 

I believe this is a duplicate of #707. Closing this in favor of that issue, feel free to re-open though if you feel like the issue is different!

**Closed by joshblack** 2018-03-19 19:40 UTC
