### ISSUE TITLE
DatePicker onChange returning undefined

### ISSUE THREAD

**Issue by apollomusa** [carbon-design-system/carbon-components-react#432] opened 2018-01-02 16:51 UTC
I'm using the DatePicker component:

```
        <DatePicker
          id="date-picker"
          datePickerType="single"
          onChange={e => this.handleDatePicker(e)}
        >
          <DatePickerInput
            labelText={
              <div className={styles.sidebarDatePickerLabel}>
                <FormattedMessage id="sidebar.from" />
              </div>
            }
            placeholder="12/30/2017"
            id="date-picker-input-id-from"
            onClick={e => this.handleDatePicker(e)}
            onChange={e => this.handleDatePicker(e)}
          />
        </DatePicker>
```

And the handler function:

```
 handleDatePicker = e => {
    console.log(e)
  }
```

The `onChange` only returns `undefined` - sounds similar to [#286](https://github.com/carbon-design-system/carbon-components-react/issues/286)

**Comment by joshblack** [comment] 2018-01-03 16:18
Hi @apollomusa! 👋  Thanks so much for taking the time to make this issue 😄

Like you mentioned, I think this is a duplicate of #286 so will close this in favor of that issue. Both should be addressed by #419, I believe! Feel free to re-open this issue, by the way, if you feel like that issue doesn't address all your concerns!

**Closed by joshblack** 2018-01-03 16:18 UTC
