### ISSUE TITLE
[Tooltip]: `clickToOpen={true}` still returning console warning

### ISSUE THREAD

**Issue by rob-richards** [carbon-design-system/carbon-components-react#2097] opened 2019-03-26 17:52 UTC
## Detailed description

When we pass clickToOpen (true) to the `<Tooltip>` component, we are still getting the console error warning us to not use `clickToOpen=false`.

```Warning: The `clickToOpen=false` option in `Tooltip` component is being updated in the next release of `carbon-components-react`. Please use `TooltipIcon` or `TooltipDefinition` instead.```

Also, the last part of the warning is a little bit confusing. Is it saying to only use the `TooltipIcon` or `TooltipDefinition` components if we want a tooltip with open on hover functionality?

Here is how we are passing the boolean.
`<Tooltip  clickToOpen tabIndex={0} triggerText="">`

**Comment by asudoh** [comment] 2019-03-27 01:26
Hi 👋 thank you for reporting! Quickly tried dropping below code into https://codesandbox.io/s/github/IBM/carbon-components-react/tree/master/examples/codesandbox, but didn't reproduce the problem. That said, would you want to try creating a reduced case?

```javascript
import React from 'react';
import { render } from 'react-dom';
import { Tooltip } from 'carbon-components-react';

const App = () => (
  <div>
    <Tooltip clickToOpen tabIndex={0} triggerText="" />
  </div>
);

render(<App />, document.getElementById('root'));
```

BTW:

> Is it saying to only use the TooltipIcon or TooltipDefinition components if we want a tooltip with open on hover functionality?

Yes. CC @IBM/carbon-designers just to double-check.

**Comment by rob-richards** [comment] 2019-03-27 15:59
Hey @asudoh - I did some more troubleshooting and it's only happening in our dev environment and on the first render. All subsequent renders do not have the error.

**Comment by asudoh** [comment] 2019-03-28 01:15
OK let us know if you find anything more while you are debugging - Thanks!

**Comment by vpicone** [comment] 2019-03-28 01:54
@rob-richards for context, our deprecation warnings only happen on the first render and in dev environments. I'm not sure how that prop is showing up falsy though, can't reproduce.

If it helps any, I believe you were right about the second sentence of the warning. It should read

>Please use 'TooltipIcon' or 'TooltipDefinition' if you prefer to show on hover.

**Comment by dakahn** [comment] 2019-05-03 17:43
I'm going to close this down as resolved, but happy to reopen if we need to 🏄

**Closed by dakahn** 2019-05-03 17:43 UTC
Labels: status: waiting for author's response, wontfix
