### ISSUE TITLE
RTL Toggle - It is toggled off after changing tabs.

### ISSUE THREAD

**Issue by crissm** [carbon-design-system/carbon-components-react#2233] opened 2019-04-18 01:46 UTC
RTL Toggle - If RTL is toggled on and the user change the tab and return to RTL tab, the toggle turns off, but the component remain in RTL.

It is happening for all components.

Browsers: Chrome, Safari, FF

I found this during some test on storybook of Maximo React Component and could reproduce it in Carbon because we are using Carbon (10)

## Steps to reproduce the issue

1. Enter this url: http://react.carbondesignsystem.com/
2. Select any component
3. Select "RTL" tab
4. Turn on the Left-to-right toggle
Note that component is now RTL
5. Change to another tab. For example "Readme" tab
6. Return to "RTL" tab

Actual Result:  Left-to-Right is toggled off, but the component remains in RTL.
Expected Result: Left-to-Right Toggle should remains selected after the user change to other tab and then returns to RTL

Workaround to really toggle off the RTL after the action above: The user select toggle on again, then toggle off.

![image](https://user-images.githubusercontent.com/33586050/56330640-578a9c80-615f-11e9-9c92-a17848ece15d.png)

**Comment by asudoh** [comment] 2019-05-03 22:55
Duplicate of: #2314.

**Closed by asudoh** 2019-05-03 22:55 UTC
Labels: priority: high, status: needs first aid
