### ISSUE TITLE
OverFlowMenu positioning is off with newest release

### ISSUE THREAD

**Issue by KSquibbs** [carbon-design-system/carbon-components-react#773] opened 2018-04-02 20:40 UTC
Whatever changes were just released broke the positioning of overflow menus embedded in tables. Both images below are the result of clicking on the overflow menu for the first row of the table.

**From version 5.36.0:**
![screen shot 2018-04-02 at 4 35 00 pm](https://user-images.githubusercontent.com/10832497/38215033-632af36a-3694-11e8-820e-625c488976b9.png)

**From version 5.39.1:**
![screen shot 2018-04-02 at 4 36 05 pm](https://user-images.githubusercontent.com/10832497/38215059-788b6014-3694-11e8-85cc-016c292b00b4.png)

**Comment by joshblack** [comment] 2018-04-02 20:41
Hi @KSquibbs! 👋 Thanks so much for taking the time to make this issue. Digging into this now 😄

**Comment by joshblack** [comment] 2018-04-02 20:48
Seems like we had two releases that included OverflowMenu code changes: https://github.com/carbon-design-system/carbon-components-react/pull/697 https://github.com/carbon-design-system/carbon-components-react/pull/770

#770 is just a prop type change, do you think we had a regression in #697 @asudoh ?

**Comment by asudoh** [comment] 2018-04-02 21:42
Quick re-run of manual against non-table floating version of overflow menu with the latest `carbon-components`/`carbon-components-react` didn't reveal the position issue described in this issue. Overflow menu in table in `carbon-components` doesn't have the problem either.

@KSquibbs Do you have a URL of the service where the problem reproduces? Thanks!

**Comment by psachs21** [comment] 2018-04-03 17:34
This looks like a similar issue to what i ran into, fixed with https://github.com/carbon-design-system/carbon-components-react/pull/769

**Comment by joshblack** [comment] 2018-04-04 15:39
Closing due to #769. Feel free to re-open if the issue still exists!

**Closed by joshblack** 2018-04-04 15:39 UTC

**Comment by KSquibbs** [comment] 2018-04-04 16:09
Just confirmed that #769 fixed this issue. Thank you.
