### ISSUE TITLE
DetailsPageHeader and TableBody should not depend on Child type name to determine whether is wanted Component, as webpack uglify plugin will change component's name 

### ISSUE THREAD

**Issue by Noodles006** [carbon-design-system/carbon-components-react#58] opened 2017-06-22 03:41 UTC

**Comment by AnthonyOliveri** [comment] 2017-08-08 23:41
I think I may have run into this issue. In the /developer console, we have a `DetailsPageHeader` that does not render properly in Bluemix (only shows the title and default icon), though it works fine when running locally. We are using the uglify plugin when deploying to Bluemix, so that could explain it.

Is anyone available to work on this? If not, I could make a pull request. I'm thinking of using separate props instead of children for each nested element. For example, the DetailsPageHeader props would remove the `children` prop and add `breadcrumb`, `tabs`, `overflow`, and `icon`. I'm not sure how those props would be validated though.

**Comment by gferreri** [comment] 2017-08-09 17:52
We use this workaround in `webpack.config.js`:

```
plugins: [
        uglify ? new webpack.optimize.UglifyJsPlugin({
            compress: {
                warnings: false,
                unused: false
            },
            mangle: {
                // we can't change the name of DetailPageHeader children or else it won't work
                // to determine the list- https://github.com/carbon-design-system/carbon-components-react/search?utf8=%E2%9C%93&q=%22type.name%22&type=
                except: ['Breadcrumb', 'Tabs', 'OverflowMenu', 'Icon', 'TableRow', 'DatePickerInput']
            },
            sourceMap: true,
        }) : NO_OP
      ],
```

**Comment by gferreri** [comment] 2017-08-09 17:54
actually this appears to be a duplicate of #136

**Comment by AnthonyOliveri** [comment] 2017-08-09 19:07
Oh yeah, it does seem to be a duplicate. Looks like this issue can be closed as well.

Time to update my `package.json`.

**Comment by chrisdhanaraj** [comment] 2017-08-09 19:16
Hey yeah, sorry - we resolved this a little bit ago, try the latest and see if it works for you.

**Closed by chrisdhanaraj** 2017-08-09 19:16 UTC
